#Jekyll config file

#title of site
name: MyGov

#description of site
description: A personalized citizen-centric platform for accessing services, getting answers, and inviting feedback. 

#URL of site, include http://, do not include a trailing slash
url: http://benbalter.github.com/mygov.github.com

#files to exclude, array
exclude: [ 'readme.md', 'php' ]

#posts per page
paginate: 5

#number of items in RSS feed
rss_limit: 10

#permalink structure, see https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:year/:month/:day/:title/

#whether production or dev, minifies JS, bool
production: true

#prose config, see http://prose.io/help/handbook.html
prose:
  rooturl: "_posts"
  metadata:
    "_posts": |
      title: "Title of the post"
      description: "SEO friendly description"
      author: "Your Name Here"
      layout: post
      comments: true,
      category: 
      tags: 
      published: false
      
#twitter handle for widget
twitter: 
  username: "benbalter"
  count: 5
  
#disqus username
disqus_shortname: 'mygov'

#google analytics username
ga_username: 'UA-XXXXX-X'